config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :users
  resources :decks do
    resources :rounds
  end

  resources :cards do
    resources :guesses
  end
  resources :sessions

  root "decks#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/card.rb
class Card < ApplicationRecord
  has_many :guesses
  belongs_to :deck
  has_many :rounds
  # , through: :guesses
end

app/models/deck.rb
class Deck < ApplicationRecord
  has_many :rounds
  has_many :cards
  has_many :guesses
  # , through: :rounds
end

app/models/guess.rb
class Guess < ApplicationRecord
  belongs_to :card
  belongs_to :round
end

app/models/round.rb
class Round < ApplicationRecord
  has_many :guesses
  belongs_to :deck
  belongs_to :player, class_name: User
  has_many :cards, through: :deck

  def accuracy
    total_attempts = 0
    self.guesses.each {|guess| total_attempts += guess.attempts}
    (100 * (self.guesses.length.to_f / total_attempts.to_f)).to_i
  end

  def solve_first_try_count
    (self.guesses.select{|guess| guess.attempts == 1}).size
  end

  def total_attempts
    self.guesses.map{|guess| guess.attempts}.reduce(:+)
  end


  def next_unsolved_card

  #These are the remaining guesses that need to be solved
    unsolved_guesses = self.guesses.select{ |guess| guess.solved == false}
    # unsolved_guesses = self.guesses.partition{ |guess| guess.solved == false}[0]
    puts "These are unsolved_guesses:"
    p unsolved_guesses

    #This is the lowest attempts count for unsolved guesses
    least_attempts_num = unsolved_guesses.map{|guess| guess.attempts}.sort.first

    p least_attempts_num

    #This shows the next guess to solve, if there is one
    next_to_solve = unsolved_guesses.select{|guess| guess.attempts == least_attempts_num}.first

    p next_to_solve

    if unsolved_guesses.size == 0
      return nil
    else
      next_to_solve.card
    end

  end
end

app/models/user.rb
require 'bcrypt'
class User < ApplicationRecord

  has_secure_password
  validates :email, uniqueness: true

  validates_presence_of :username, :email


  has_many :rounds
  has_many :guesses
  has_many :played_decks, through: :rounds, source: :deck
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include ApplicationHelper
  protect_from_forgery with: :exception
end

app/controllers/decks_controller.rb
class DecksController < ApplicationController
  def index
    @decks = Deck.all
  end


end

app/controllers/guesses_controller.rb
class GuessesController < ApplicationController

  def show
    @card = Card.find(params[:card_id])
    @guess = Guess.find(params[:id])
    render
  end

#updates the guess
  def update
    @card = Card.find(params[:card_id])
    @deck = @card.deck
    @guess = Guess.find(params[:id])
    @round = Round.find(@guess.round_id)
    #add +1 to attempt, this might not work
    @guess.attempts += 1
    if @guess.card.answer == params[:guess][:answer].chomp
      @guess.solved = true
    end
    @guess.save

    if @guess.solved == false
      redirect_to card_guess_path(@card.id, @guess.id)
    else
      p "redirecting"
      redirect_to deck_round_path(@card.deck.id, @round.id)
    end
  end


end

app/controllers/rounds_controller.rb
class RoundsController < ApplicationController

  def show
    @round = Round.find(params[:id])
    @user = current_user
    @card = @round.next_unsolved_card

    if !@card
      render :show
    else
      @guess = Guess.find_by(card_id: @card.id, round_id: @round.id)
      render :'cards/show'
    end
  end

  def create
    @deck = Deck.find(params[:deck_id])
    @round = Round.create(deck_id: @deck.id, player_id: 1)
    @cards = @deck.cards
    @cards.each do |card|
      Guess.create(round_id: @round.id, card_id: card.id)
    end
    redirect_to deck_round_path(@deck.id, @round.id)
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    @user = User.find_by(email: params[:email]).try(:authenticate, params[:password])

    if @user
      session[:user_id] = @user.id
      redirect_to decks_path
    else
      @errors = "Incorrect email or password"
      p "you failed to login"
      render :new
    end
  end

  def destroy
    session[:user_id] = nil
    redirect_to decks_path
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      session[:user_id] = @user.id
      redirect_to decks_path
    else
      render :new
    end
  end

  private
  def user_params
    params.require(:user).permit(:username, :email, :password)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper

  def current_user
    @user ||= User.find(session[:user_id]) if session[:user_id]
  end

  def current_user_id
    current_user.id if current_user
  end

  def logged_in?
    !!current_user
  end
end

app/views/cards/show.html.erb
<h2>Guess the Answer</h2>
<h3 style="white-space: pre-wrap"><%= @card.question %></h3>

<% if @attempted %>
  <h4> The correct answer was:</h4>
  <p><%= @card.answer %></p>
  <%= link_to 'Next Question', deck_round_path(@deck.id, @round.id) %>
<% else %>
  <%= form_with model: [@card, @guess] do |form| %>
    <%= form.label :answer %>
    <%= form.text_field :answer %>
    <%= form.submit %>
  <% end %>

<% end %>

app/views/decks/index.html.erb
<% if @decks %>
  <section class="deck_list">
    <% @decks.each do |deck| %>
      <section class="deck_list_item">
        <%= link_to "#{deck.name}", deck_rounds_path(deck), method: :post %>
      </section>
    <% end %>
  </section>
<% end %>

<footer>
  <% if logged_in? %>
    <p><%= link_to "Logout", session_path(1), method: :delete %></p>
  <% else %>
    <p><%= link_to "Register", new_user_path %><br><%= link_to "Login", new_session_path %></p>
  <% end %>
</footer>

app/views/guesses/show.html.erb
<h3 style="white-space: pre-wrap"><%= @card.question %></h3>

<h4> The correct answer was:</h4>
<p><%= @card.answer %></p>
<%= link_to 'Next Question', deck_round_path(@card.deck.id, @guess.round.id) %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsFlashcard</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <h1>Flashcards!</h1>
    <%= yield %>
  </body>
</html>

app/views/rounds/show.html.erb
<% if logged_in? %>
  <h2>Good job <%= @user.username %>! You completed the deck</h2>
<% else %>
   <h2>Good job! You completed the deck</h2>
<% end %>

<h4>Here's how you did:</h4>
<ul>
  <li>You successfully completed <%= @round.deck.cards.length %> questions</li>
  <li>You answered with <%= @round.accuracy %>% accuracy</li>
  <li>You answered <%= @round.solve_first_try_count %> of <%= @round.cards.size %> cards correctly on the first try</li>
  <li>You submitted <%= @round.total_attempts %> total guesses before this deck was completed</li>
</ul>

<%= link_to 'Take me home', decks_path %>

app/views/users/_form.html.erb
<%= form_with model: user, local: true do |form| %>
  <% if user.errors.any? %>
      <h4><em>The following prevented your account from being created:</em></h4>
      <ul>
        <% user.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
  <% end %>

  <%= form.label :username %>
  <%= form.text_field :username %>

  <%= form.label :email %>
  <%= form.text_field :email %>

  <%= form.label :password %>
  <%= form.password_field :password %>

  <%= form.submit 'Create Account' %>

<% end %>

app/views/users/new.html.erb
<h3>Create an Account</h3>
<%= render 'form', user: @user %>

<%= link_to 'Home', decks_path %>